- build: examples/1-simple
  photon: [1.0.0, 1.1.0, 1.2.1, 1.3.1, 1.4.2]
  p1: [1.0.0,latest]
  electron: [1.1.0,latest]
  argon: [0.9.0, 1.1.0, latest]
  boron: [1.2.1, latest]
  xenon: [1.5.2]
- build: examples/2-line-editing
  argon: [latest]
- build: examples/3-line-editing-uart
  argon: [latest]
- build: examples/4-print-message
  argon: [latest]
- build: examples/5-log-handler
  argon: [latest]
- build: examples/6-tcp-server
  argon: [latest]

  